function b = CheckSimpleNorth(n)
% CHECKSIMPLENORTH Checks for each row in matrix n if the specified binary
% neighborhood is simple and has a north boundary. 
%
%  USAGE: b = CheckSimpleNorth(n, varargin)
%
%  OUTPUT
%	b:  Logical Nx1 array that specifies for each row in n, if a pixel with 
%       neighborhood n(i,:) is simple and has a north boundary.
%
% __________________________________________________________________________
%  INPUTS
%	n:  Local neighborhood of pixel(s) (Nx8 logical array) where each rows 
%       represents a separate neighborhood, n(:,1) is the north pixel and 
%       subsequent pixels are labeled in clock wise order n(:,2) to n(:,8).
%
% __________________________________________________________________________
%  VARARGIN
%	See 'Parameter Initialization' section ...
%

% ------------------------------- Version 1.0 -------------------------------
%	Author:  Martin Wagner
%	Email:     mwagner9@wisc.edu
%	Created:  2019-04-03
% __________________________________________________________________________

%% Solve Boolean Equation
b = ~n(:,1) & ...
    ( ...
        ( ...
            ~n(:,2) & ~n(:,8) & ...
            xor(xor(n(:,3), n(:,4)), ~n(:,5)) & ...
            xor(n(:,4), n(:,6)) & ...
            xor(n(:,4), n(:,7)) ...
        ) | ...
        (n(:,3) & n(:,5) & ~n(:,8)) | ...
        (~n(:,2) & n(:,5) & n(:,7)) | ...
        ( ...
            xor(n(:,2), n(:,6)) & ...
            xor(n(:,3), n(:,6)) & ...
            xor(n(:,5), ~n(:,6)) & ...
            ~n(:,7) & ...
            ~n(:,8) ...
        ) | ...
        (n(:,3) & n(:,5) & n(:,7)) | ...
        (~n(:,2) & ~n(:,3) & ~n(:,4) & n(:,7) & n(:,8)) ...
    );
    
